services:
  redis:
    image: redis:latest
    container_name: dred-redis
    ports:
      - '6379:6379'
  dred:
    build: ./
    container_name: dred
    ports:
      - '3000:3000'
    depends_on:
      - 'redis'
