version: "3"
services:
  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - '6379:6379'
  dred:
    build: ./
    environment:
      - 'REDIS_URL=redis://default:@redis:6379'
    ports:
      - '3000:3029'
    depends_on:
      - 'redis'
