packages:
  - 'src/client'  
  - 'docs'
  - 'sampleApp'
  - 'vendor/poshplum/packages/poshplum'
  - 'vendor/poshplum/packages/utils'
  - '.'

  # works better with yarn used in that subdir:
  # - 'src/redis/streams'
  
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/__tests__/**'
  

