packages:
  - 'src/client'  
  - 'docs'
  - 'sampleApp'
  - 'onchain'
  - '.'
  # - '../stellar-contracts'
  # works better with yarn used in that subdir:
  # - 'src/redis/streams'
  
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/__tests__/**'
  

overrides:
  "@donecollectively/stellar-contracts": "$@donecollectively/stellar-contracts"
  # ^ merge the resolution of this package so it will resolve as a transitive dependency to ONE package.
  # vv 👁️ use local override for stellar-contracts/tokenomics local dev, commenting out the first override ^^
  #  "@donecollectively/stellar-contracts": "file:../stellar-contracts"
  #          use this vvv instead of ^ for rapid iteration of stellar-contracts (see package.json notes too)
  # "@donecollectively/stellar-contracts": "../stellar-contracts"
  # "stellar-tokenomics": "../stellar-tokenomics"
  # 👁️  ^^ don't check it in with these local overrides
  "react": "$react"
  "react-dom": "$react-dom"
  