packages:
  - 'src/client'  
  - 'docs'
  - 'sampleApp'
  - 'onchain'
  - '../stellar-contracts'
  - '.'

  # works better with yarn used in that subdir:
  # - 'src/redis/streams'
  
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/__tests__/**'
  

overrides:
  "@donecollectively/stellar-contracts": "$@donecollectively/stellar-contracts"
  # ^ merge the resolution of this package so it will resolve as a transitive dependency to ONE package.
  "react": "$react"
  "react-dom": "$react-dom"
  