#!/bin/bash


if [[ -z $DEBUG ]] ; then
  node_modules/rollup/dist/bin/rollup --config rollup.config.ts \
  --importAttributesKey "with" \
  --configPlugin 'esbuild={sourcemap:true,supported:{"import-assertions":false},loaders:{".json": "json"}, target: "esnext", tsconfig:"./tsconfig.rollupconfig.json"}' \
  $@
else
    scripts/debugRollup $@
fi

