# DRED Pre-Production Server Configuration
# Server IP addresses (detailed config in config/ directory)

# Preprod servers (tested and working)
US=74.208.13.84
UK=217.154.34.155


# Ben's Test server for dockerization
DE=85.215.215.192


# Add more servers here as needed
# Example:
# FR=192.168.1.101
# JP=192.168.1.102 