# This is the original working workflow to build docs. 
# We renamed to .bak to preserve a copy. 


name: Deploy Next.js Documentation

on:
  push:
    branches: [ main, dev/patrik, feature/docs-with-registry ]
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.15.4
          run_install: false
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          
      - name: Install dependencies
        run: |
          cd docs && pnpm install --frozen-lockfile
          cat node_modules/@donecollectively/stellar-contracts/package.json
        
      - name: Build documentation
        env:
          NEXT_PUBLIC_BASE_PATH: /dred
          NEXT_PUBLIC_BF_API_KEY: ${{ vars.NEXT_PUBLIC_BF_API_KEY }}
        run: cd docs && pnpm run build 
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Output deployment URL
        run: echo "Documentation deployed to ${{ steps.deployment.outputs.page_url }}" 
